# screen constant
SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 900

# arrow constant
ARROW_WIDTH = 164
ARROW_HEIGHT = 116

# move constant
MOVE_HORIZONTALY = 0
MOVE_VERTICALY = 0
MOVE_LEFT = -1
MOVE_RIGHT = 1
MOVE_UP = -1
MOVE_DOWN = 1

# Coulors
WHITE = (255, 255, 255)
BLACK = (0, constant.MOVE_HORIZONTALY, constant.MOVE_HORIZONTALY)
GREEN = (0, 255, constant.MOVE_HORIZONTALY)